name: Android Build CI

on: [push]

jobs:
  build:
    
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Dependencies
        run: npm ci
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
        with:
          cordova-version: 8
      - name: Build
        run: |
          ionic cordova build android --prod
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: /home/runner/work/Frontend_User/Frontend_User/platforms/android/app/build/outputs/apk/debug/app-debug.apk
  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download APK
        uses: actions/download-artifact@v1
        with:
          name: app
      
      - name: Path
        run: ls path/to/artifact
      
      - name: App Center
        uses: wzieba/AppCenter-Github-Action@v1.0.0
        with:
          # App name followed by username e.g. wzieba/Sample-App
          appName: WirVsVirusCovidTestProcress/CoronaTestAndroid
          token: ${{ secrets.appcenter }}
          group: Collaborators
          # Artefact to upload (.apk or .ipa)
          file: /home/runner/work/Frontend_User/Frontend_User/app/app/app-debug.apk
          # Release notes visible on release page
          # releaseNotes: # optional
    
